name: 'Publish Tauri App'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install web dependencies
        working-directory: ./desktop
        run: npm install

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: './desktop'
          tagName: v1.0.0-${{ github.sha }} # The action automatically creates a release
          releaseName: 'LightShot Clone v1.0.0'
          releaseBody: 'Automatic build of the desktop app.'
          releaseDraft: true
          prerelease: false
